spring.application.name=log-analyzer

# Database Configuration with Docker Environment Overrides
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/logdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Groq API Key Configuration
groq.api.key=${GROQ_API_KEY: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}